### ISSUE TITLE
Force option does not work

### ISSUE THREAD

**Issue by julytn** [schnittstabil/lnk#3]
### Problem
When the symlink already exists and has `EEXIST` error code, it throws an error instead of updating the symlink given the force option. 

In these 2 places, the `||` should be a `&&`: https://github.com/schnittstabil/lnk/blob/eaa14ca5d34d2727641849d57508ef8af650b26e/index.js#L30 and https://github.com/schnittstabil/lnk/blob/eaa14ca5d34d2727641849d57508ef8af650b26e/index.js#L55

**Comment by schnittstabil** [comment]
I don't think so. Please note `rimraf.sync`, which tries to remove existing files:
https://github.com/schnittstabil/lnk/blob/eaa14ca5d34d2727641849d57508ef8af650b26e/index.js#L55-L61

And it is tested by:
https://github.com/schnittstabil/lnk/blob/eaa14ca5d34d2727641849d57508ef8af650b26e/test/index.js#L109-L116

If you still get an error, it might be due to missing rights.
